# Generated by Django 4.2.1 on 2023-08-20 11:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("image", "0001_initial"),
        ("bookmark", "0002_alter_bookmark_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="bookmark",
            name="image",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bookmark_images",
                to="image.image",
            ),
        ),
    ]
